apiVersion: v1
kind: Service
metadata:
  name: {{ include "tech-challenge-app.fullname" . }}
  labels:
    {{- include "tech-challenge-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
      protocol: TCP
      name: http
  selector:
    {{- include "tech-challenge-app.selectorLabels" . | nindent 4 }}
