apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-admin-secret
  labels:
    app: {{ include "tech-challenge-app.fullname" . }}
data: ## colocar tudo em base64
  DB_PORT: 'MzMwNg==' # 3306
  DB_USER: 'dGVjaC11c2Vy' # tech-user
  DB_PASSWORD: 'dGVjaC1wYXNz' # tech-pass
  DB_NAME: 'dGVjaC1jaGFsbGVuZ2U=' #tech-challenge
  DB_ROOT_PASSWORD: 'dGVjaC1wYXNz' # tech-pass