{{- if .Values.database.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tech-challenge-database-pv
  labels:
    app: {{ include "tech-challenge-app.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.database.persistentVolume.storage }}
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: tech-challenge-database-local-storage-class
  {{- if eq .Values.database.persistentVolume.platform "docker-desktop-windows" }}
  local:
    path: {{ printf "%s%s" "/run/desktop/mnt/host" .Values.database.persistentVolume.localPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
  {{ else }}
  hostPath:
    path: {{ .Values.database.persistentVolume.localPath }}
    type: DirectoryOrCreate
  {{ end }}
{{ end }}