{{- if .Values.database.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tech-challenge-database-pvc
  labels:
    app: {{ include "tech-challenge-app.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: tech-challenge-database-local-storage-class
  resources:
    requests:
      storage: {{ .Values.database.persistentVolume.storage }}
{{ end }}