apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tech-challenge-db-pvc
  namespace: tech-challenge
  labels:
    app: tech-challenge-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi