apiVersion: v1
kind: PersistentVolume
metadata:
  name: tech-challenge-db-pv
  namespace: tech-challenge
  labels:
    app: tech-challenge-app
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  # hostPath:
  #   path: /run/desktop/mnt/host/c/tech-challenge-data
  #   type: DirectoryOrCreate
  local:
    path: /run/desktop/mnt/host/c/tech-challenge-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop