apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-deployment
  namespace: tech-challenge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tech-challenge-app
  template:
    metadata:
      labels:
        app: tech-challenge-app
    spec:
      containers:
        - name: tech-challenge
          image: loadinggreg/tech-challenge:latest
          envFrom:
            - configMapRef:
                name: tech-challenge-config-map
            - secretRef:
                name: tech-challenge-secret

          ports:
            - containerPort: 8080
              name: http
              protocol: TCP