apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-svc
  namespace: tech-challenge
spec:
  selector:
    app: tech-challenge-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30808
  type: NodePort