apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-svc-db
  namespace: tech-challenge
spec:
  selector:
    app: tech-challenge-db
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 32060
  type: NodePort