apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-core-deployment
  namespace: tech-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-app
  template:
    metadata:
      labels:
        app: tech-challenge-app
    spec:
      containers:
        - name: tech-challenge-app
          image: loadinggreg/tech-challenge:latest
          envFrom:
            - configMapRef:
                name: tech-challenge-config-map
            - secretRef:
                name: tech-challenge-admin-secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP